# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3797f54bd4e44c61d242a926d232fea4fd5ab1a295dc5fe23c07778f627417d9c7da7383adb50a81874e0ccd0d9cb2d0db4fb621b1e5128efd276f4c984c85

test:
  secret_key_base: 997752dd9d5415cbe3567bacb209980a2751066fe031c570a59b5836659f93ac725de18f759bfff90db80b9467f8e8b1cea67e99a7d97d87026ade99c8f12f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
